"""empty message

Revision ID: 3e2d4c64417d
Revises: 
Create Date: 2024-06-08 15:34:10.677565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2d4c64417d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('working_hours_doctor_id_key', 'working_hours', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('working_hours_doctor_id_key', 'working_hours', ['doctor_id'])
    # ### end Alembic commands ###
